sudo: required

service:
  - docker

language: go

go:
  - 1.12.1

go_import_path: turtles-licenserec

#install:
  #- make


after_success:
  #- cd $GOPATH/_infra
  #- ./after_success.sh
  - docker --version  # document the version travis is using
  - pip install --user awscli # install aws cli w/o sudo
  - export PATH=$PATH:$HOME/.local/bin # put aws in the path
  - pwd
  - cd $GOPATH/src/turtles-licenserec/license_rec_api
  - docker build -t turtles-licenserec .
  - docker image ls
  - docker tag turtles-licenserec:latest 754533604493.dkr.ecr.ap-southeast-2.amazonaws.com/flexera/turtles/innovations:latest
  - $(aws ecr get-login --no-include-email --region ap-southeast-2)
  - docker push 754533604493.dkr.ecr.ap-southeast-2.amazonaws.com/flexera/turtles/innovations:latest


